"""Prove the CNF says exactly what the definition says.

Asymmetry of risk.  The lower bound ships a certificate: a reader checks the
colouring against the definition and never has to trust our code.  The upper
bound has no such artifact -- "no colouring of [1,n] exists" is a claim about
the *absence* of an object, and it is only as good as the claim that the CNF
handed to the solver is a faithful translation of the problem.  A single wrong
clause and the solver dutifully proves UNSAT for the wrong question.

So the encoding is audited by exhaustion on instances small enough to enumerate:

  TEST 1  (faithfulness)  With symmetry breaking off, the set of colourings
          satisfying the CNF must be *exactly* the set that `check` accepts,
          where `check` is a direct transcription of the definition that never
          looks at a clause.  Equality both ways: no solution invented, none
          lost.

  TEST 2a (symmetry breaking is SOUND -- must hold)  Every orbit of the
          symmetry group must keep at least one representative.  Lose an orbit
          and the solver can report UNSAT for a satisfiable instance, which is
          precisely how a wrong new term gets published.

  TEST 2b (symmetry breaking is COMPLETE -- want, but only costs time)  Every
          orbit keeps at most one.  Duplicates just mean the search does work
          twice.

Measured outcome: 2a holds everywhere.  2b holds exactly on the families with
*distinct* targets -- including [3,4], the family being extended -- and leaves
two representatives per orbit on the equal-target families ([3,3], [4,4],
[3,3,3]).  That is expected: the colour-swap breaker and the reversal breaker
are each a lex-leader for their own subgroup, but composing two independent
breakers does not in general canonicalise the group they generate, so
(swap o reverse) can carry one survivor to another.  For [3,4] the colour-swap
subgroup is trivial, the group is just {identity, reversal}, and the breaking
is exactly canonical.

The group is generated by the reversal i -> n+1-i and by permutations of
colours that share a target value.  Both genuinely fix the problem, so the
orbit of any valid colouring consists of valid colourings.

Usage:  python encoding_audit.py
"""
import itertools
import sys

from pysat.solvers import Cadical195

from vdw4 import build, check


def brute_force(n, j, targets):
    """Every colouring the definition allows, by exhaustive enumeration."""
    r = len(targets)
    out = set()
    for assign in itertools.product(range(r + 1), repeat=n):
        if check(list(assign), targets, j)[0]:
            out.add(assign)
    return out


def all_models(n, j, targets, symbreak, revsym):
    """Every colouring the CNF allows, enumerated by blocking projections."""
    r = len(targets)
    cnf, pool, v = build(n, j, targets, symbreak=symbreak, revsym=revsym)
    found = set()
    with Cadical195(bootstrap_with=cnf) as s:
        while s.solve():
            model = set(l for l in s.get_model() if l > 0)
            col = tuple(next(c for c in range(r + 1) if v(i, c) in model)
                        for i in range(1, n + 1))
            found.add(col)
            s.add_clause([-v(i + 1, c) for i, c in enumerate(col)])
    return found


def group_elements(n, targets):
    """The symmetry group as explicit maps on colourings: reversal composed
    with every permutation of each equal-target colour block."""
    r = len(targets)
    groups = {}
    for c, t in enumerate(targets, start=1):
        groups.setdefault(t, []).append(c)

    colour_maps = [{}]
    for t, cols in groups.items():
        new = []
        for perm in itertools.permutations(cols):
            for base in colour_maps:
                m = dict(base)
                m.update(dict(zip(cols, perm)))
                new.append(m)
        colour_maps = new

    def apply(col, cmap, rev):
        out = tuple(cmap.get(c, c) for c in col)
        return tuple(reversed(out)) if rev else out

    return [(cmap, rev) for cmap in colour_maps for rev in (False, True)], apply


def orbits(valid, n, targets):
    els, apply = group_elements(n, targets)
    seen, out = set(), []
    for col in valid:
        if col in seen:
            continue
        orb = {apply(col, cmap, rev) for cmap, rev in els}
        seen |= orb
        out.append(orb)
    return out


CASES = [
    # (n, j, targets)  -- small enough to enumerate (r+1)^n
    (8,  0, [3, 4]),
    (10, 1, [3, 4]),
    (12, 2, [3, 4]),
    (11, 3, [3, 4]),
    (9,  1, [3, 3]),          # equal targets: colour-swap symmetry is live
    (11, 2, [3, 3]),
    (8,  1, [3, 3, 3]),       # three colours
    (9,  2, [4, 4]),
    (10, 0, [3, 5]),
    # A217236's shape. Added 2026-07-31, when documenting that term made it plain
    # that [4,5] was the one target pair carrying a new claim while never having
    # been audited against the definition. Documenting a gap is not the same as
    # closing it.
    (10, 0, [4, 5]),
    (11, 1, [4, 5]),
]


def main():
    fails = 0
    for n, j, targets in CASES:
        valid = brute_force(n, j, targets)
        plain = all_models(n, j, targets, symbreak=False, revsym=False)

        t1 = (plain == valid)
        missing = len(valid - plain)
        invented = len(plain - valid)

        broken = all_models(n, j, targets, symbreak=True, revsym=True)
        orbs = orbits(valid, n, targets)
        hits = [len(o & broken) for o in orbs]
        lost = sum(1 for h in hits if h == 0)

        t2a = (broken <= valid) and lost == 0          # soundness: nothing lost
        t2b = all(h == 1 for h in hits)                # completeness: no dupes

        ok = t1 and t2a                                # only these can be wrong
        fails += 0 if ok else 1
        note = 'canonical' if t2b else f'{len(broken)-len(orbs)} dupes'
        print(f'n={n:3d} j={j} t={str(targets):9s} '
              f'valid={len(valid):7d} cnf={len(plain):7d} '
              f'orbits={len(orbs):6d} kept={len(broken):6d}  '
              f'faithful={t1} no-orbit-lost={t2a} {note:14s} '
              f'{"ok" if ok else "*** FAIL ***"}', flush=True)
        if not t1:
            print(f'      lost {missing} solutions, invented {invented}')
        if lost:
            print(f'      *** {lost} ORBITS LOST -- false UNSAT is possible ***')

    print()
    if fails:
        print(f'{fails}/{len(CASES)} cases FAILED -- encoding is not trustworthy')
        return 1
    print(f'all {len(CASES)} cases pass.')
    print('  the CNF accepts exactly the colourings the definition accepts')
    print('  symmetry breaking never removes an orbit, so UNSAT is never spurious')
    print('  on distinct-target families ([3,4] included) it is exactly canonical')
    return 0


if __name__ == '__main__':
    sys.exit(main())
